topic/urls.py
from django.urls import path
from topic.views import release, topic_index, discuss, comment, get_reply, collection, comment_loc, topic_loc, \
    search_topic, modify, adoption

app_name = 'topic'

urlpatterns = [
    path('release/', view=release, name='release'),
    path('modify/', view=modify, name='modify'),
    path('area/<area>/', view=topic_index, name='topic_index'),
    path('search/', view=search_topic, name='search_topic'),
    path('discuss/<topic_id>/', view=discuss, name='discuss'),
    path('comment/<topic_id>/add', view=comment, name='comment'),
    path('get_reply/', view=get_reply, name='get_reply'),
    path('collection/', view=collection, name='collection'),
    path('comment_loc/', view=comment_loc, name='comment_loc'),
    path('topic_loc/', view=topic_loc, name='topic_loc'),
    path('adoption/', view=adoption, name='adoption')
]

user/urls.py
from django.urls import path
from user.views import registered, login, logout, user_index, leave_message, mailbox, get_message, del_message, \
    settings, bind_email, modify_password, application_reset_password, reset_password, modify_personal_information

app_name = 'user'
urlpatterns = [
    path("registered/", view=registered, name='registered'),
    path('login/', view=login, name='login'),
    path('logout/', view=logout, name='logout'),
    path('user_index/<user_nickname>/', view=user_index, name='user_index'),
    path('leave_message/', view=leave_message, name='leave_message'),
    path('mailbox/', view=mailbox, name='mailbox'),
    path('get_message/', view=get_message, name='get_message'),
    path('del_message/', view=del_message, name='del_message'),
    path('settings/', view=settings, name='settings'),
    path('settings/bind_email/', view=bind_email, name='bind_email'),
    path('settings/modify_password/', view=modify_password, name='modify_password'),
    path('settings/modify_personal_information/', view=modify_personal_information, name='modify_personal_information'),
    path('reset_password/application', view=application_reset_password, name='application_reset_password'),
    path('reset_password/<code>', view=reset_password, name='reset_password')
]

xuetang/urls.py
from django.contrib import admin
from django.urls import path, include
from xuetang.views import home, upload, get_verification, send_code

urlpatterns = [
    path("user/", include("user.urls")),
    path('topic/', include('topic.urls')),
    path('audit/', include('audit.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', view=home, name="home"),
    path('home/', view=home, name="home"),
    path('upload/', view=upload, name='upload'),
    path("get_verification/", view=get_verification, name='get_verification'),
    path('send_code/', view=send_code, name='send_code')
]

topic/models.py
from django.db import models

# Create your models here.

topic/views.py
import operator
from functools import reduce
from django.shortcuts import render, HttpResponseRedirect, reverse, Http404
from django.http import JsonResponse
from topic.plug_ins import sort_out_tag, save_topic, get_topic, modify_loc, get_paginator, adoption_review
from .models import Area, Topic, Comment, Collection, Tag
from django.db.models import Q
from xuetang.plug_ins import get_user


# Create your views here.


def release(request):
    """发布话题
    :param request:
    :return:返回发布话题所在页面,未完成.返回发布结果信息.未完成
    """
    tags = request.POST.get('tags').split()

    # 保存话题
    topic = save_topic(request)

    if tags:
        # 如果有标签,创建标签,简历标签与话题关系
        sort_out_tag(topic, tags)
    return HttpResponseRedirect(reverse('topic:topic_index', args=[topic.area_id.path_name]))


def modify(request):
    """话题编辑页面与处理编辑内容
    :param request:
    :return: GET返回编辑页面,POST返回话题讨论页.
    """
    if request.method == 'GET':
        topic_id = request.GET.get('topic_id')
        topic = Topic.objects.filter(id=topic_id).first()
        content = {
            'title': '编辑话题',
            'topic': topic
        }
        return render(request, template_name='topic/modify.html', context=content)
    else:
        tags = request.POST.get('tags').split()
        topic_id = request.POST.get('topic_id')
        topic = Topic.objects.filter(id=topic_id).first()
        topic = save_topic(request, topic)
        sort_out_tag(topic, tags)
        return HttpResponseRedirect(reverse('topic:topic_index', args=[topic.area_id.path_name]))


def topic_index(request, area):
    """话题分区视图.
    :param request:
    :param area: 分区代号,作为筛选话题的主要条件之一.与前台sort分类标识
    :return: 话题列表
    """
    # 获取分区话题
    topics = get_topic(request, {'area_id__path_name': area})
    # 获取分区名,返回给前台title
    area_name = Area.objects.filter(path_name=area).first().name
    # page:请求页数 paginator:分页对象 page_list:处理过后的分页数
    page = int(request.GET.get('page', 1))
    topic, paginator, page_list = get_paginator(page, topics)
    content = {
        'title': area_name,
        'args': 'sort=' + request.GET.get('sort', ''),
        'area': area,
        'page': page,
        'topics': topic,
        'paginator': paginator,
        'page_list': page_list,
        'topic': True
    }
    return render(request, template_name='topic/index.html', context=content)


def search_topic(request):
    """搜索视图
    不支持tag与question双参数同时搜索.
    收集tag\question\page url参数,
    args为当前搜索内容记录,在分页导航中传入args内容.
    :param request:
    :return:
    """
    # page:请求页码,tag:标签名,question:问题内容
    page = int(request.GET.get('page', 1))
    tag = request.GET.get('tag')
    tag = Tag.objects.filter(name=tag).first()
    question = request.GET.get('question')
    # 不支持双参数同时搜索,优先搜索tag标签
    if tag:
        # topics: 获取话题中,外键id等于tag,并且状态为true的所有话题集合
        topics = get_topic(request, {'tags__tag_id': tag.id, 'status': True})

        # 将topics交给get_paginator处理获得指定页数,指定每页内容的topic 返回前台呈现
        topic, paginator, page_list = get_paginator(page=page, topics=topics, per_page=20)

        # args:url参数,维持分页功能.
        args = 'tag=' + tag.name
        title = tag.name

    elif question:
        # 查找关键词中包含的第一个标签,供前台呈现.
        for i in question.split():
            tag = Tag.objects.filter(name=i).first()
            # 查找第一个,找到即不再继续.
            if tag:
                break

        # Q_obj:多参数模糊查询.底层机制完全不知道.待解决.
        Q_obj = reduce(operator.or_,
                       ([Q(**{'title__icontains': i}) | Q(**{'content__icontains': i}) for i in question.split()]))

        # 获取话题集合
        topics = get_topic(request, Q_obj=Q_obj)

        # 获取分页相关数据
        topic, paginator, page_list = get_paginator(page=page, topics=topics, per_page=20)

        # args:url参数,维持搜索分页功能.
        args = 'question=' + question
        title = question
    else:
        return Http404
    content = {
        'title': title,
        'page': page,
        'topics': topic,
        'paginator': paginator,
        'page_list': page_list,
        'args': args,
        'tag': tag
    }
    return render(request, template_name='topic/index.html', context=content)


def discuss(request, topic_id):
    """话题讨论页面
    :param request:
    :param topic_id: 话题id
    :return: 返回话题内容页面
    """
    page = int(request.GET.get('page', 1))
    topic = Topic.status_true.filter(id=topic_id).first()

    comments = topic.comments.filter(status=True, reply_obj_id=None, adoption=False).all()
    comments, paginator, page_list = get_paginator(page, comments, per_page=20)

    if page == 1:  # 第一页 需要展示被采纳的评论
        adoption_ = topic.comments.filter(status=True, adoption=True).first()  # 查找被采纳的评论
        if adoption_:  # 当被采纳的评论存在时
            comments = list(comments)  # 列表化评论集合
            comments.insert(0, adoption_)  # 插入评论

    contents = {
        'title': topic.title,
        'area': topic.area_id.path_name,
        'topic': topic,
        'comments': comments,
        'paginator': paginator,
        'page_list': page_list,
        'page': page
    }
    return render(request, template_name='topic/discuss.html', context=contents)


def comment(request, topic_id):
    """处理评论请求
    :param request:
    :param topic_id: 话题id,定位评论与话题关系
    :return: 当请求属于reply回复评论时,返回状态信息等...当请求属于评论时,跳转至话题页面,并携带message信息.
    """
    # 获取user判断评论有效性 obj判断是否为回复
    user = get_user(request)
    content = request.POST.get('comment', None)
    obj = request.POST.get('reply', None)
    kwargs = {'reply_obj_id': obj} if obj else {}
    # 以url参数message=xxx的方式传递给给前台的消息反馈,具体消息在前台js文件内.
    message = '?'
    if user:
        # 当用户帐号未激活时,将评论状态改为待审核,并做出相应提示.
        if user.level == 0:
            kwargs.update({'status': False})
            message += 'message=comment-level'
        comment = Comment(user_id=user.user, topic_id_id=topic_id, content=content, **kwargs)
        comment.save()
    else:
        # 获取游客ip message提示评论需要审核
        ip = request.META['REMOTE_ADDR']
        message += "message=comment-audit"
        comment = Comment(user_id='AdminAudit', status=False, topic_id_id=topic_id, content=content, ip=ip, **kwargs)
        comment.save()
    # 如果有reply对象,请求则为ajax请求,返回前台所需的反馈信息.
    if obj:
        # reply回复功能,不允许未登入用户回复,
        return JsonResponse({'status': 'ok', 'user': comment.user.nickname, 'content': comment.content})
    else:
        return HttpResponseRedirect(reverse('topic:discuss', args=[topic_id]) + message)


def get_reply(request):
    """获取指定评论对象,得到回复数据,以json格式返回给前台,由前台渲染呈现.
    :param request:
    :return: 返回状态码,replys:回复集合. replys是由n个{user:xx, content:xx}组成的列表
    """
    reply = int(request.GET.get('reply'))

    # 得到全部指向评论id的状态为true的回复
    comments = Comment.objects.filter(status=True, reply_obj=reply).all()

    replys = []
    # 如果comments不为None, 循环comments 生成{user:xx, content:xx}格式的字典表,追加进replys,供前台呈现.
    if comments:
        for i in comments:
            replys.append({
                'user': i.user.nickname,
                'content': i.content
            })
    return JsonResponse({'status': 'ok', 'replys': replys})


def collection(request):
    """收藏话题请求\处理,视图.
    如果用户当前未登录,直接返回failure状态码,如果已登录,再继续做判断.
    :param request:
    :return: 状态码与相应提示信息通知
    """
    user = get_user(request)
    if user:
        topic = request.GET.get('topic')
        c = Collection.objects.filter(topic_id_id=topic, user=user).first()
        if c:
            # 用户已收藏此话题,当前请求判断为取消收藏.选择删除收藏关系
            c.delete()
            return JsonResponse({'status': 'success', 'message': 'cancel-collection'})
        else:
            # 用户未收藏此话题,建立收藏关系
            c = Collection(topic_id_id=topic, user=user)
            c.save()
            return JsonResponse({'status': 'success', 'message': 'collection-success'})
    else:
        return JsonResponse({'status': 'failure', 'message': 'collection-failure'})


def comment_loc(request):
    """comment like or contra 关系处理视图
    :param request:
    :return:
    """
    result = modify_loc(request, 'comment')
    key_id = result.pop('key_field', None)
    # 如果有key_id 表示关系处理正常,返回相关信息到前台.
    if key_id:
        return JsonResponse(result)
    else:
        return Http404


def topic_loc(request):
    """话题like or contra 关系处理视图
    从modify_loc获取关系 +- 动作结果,修改话题相关字段值
    :param request: 成功返回关系结果,否则返回404状态,前端不执行后续js操作
    :return:
    """
    result = modify_loc(request, 'topic')
    key_id = result.pop('key_field', None)

    # 如果有key_id 表示关系处理正常,修改话题相关字段值.
    if key_id:
        topic = Topic.objects.filter(pk=key_id).first()
        topic.like += result.pop('like')  # 这里有bug 在高并发的情况下容易出错.不应该查询再增减而是通过sql直接修改数据
        topic.contra += result.pop('contra')
        topic.save()
        return JsonResponse(result)
    else:
        raise Http404


def adoption(request):
    """采纳评论视图"""
    topic_id = request.POST.get('topic_id')
    comment_id = request.POST.get('comment_id')
    user_info = request.session.get('user')

    try:
        assert user_info, 'user is none'  # 验证用户是否登录
    except AssertionError as err:
        print(err)
        return JsonResponse({'code': 500, 'message': 'You do not have permission'})

    if adoption_review(topic_id=topic_id, user_user=user_info.get('user')):  # 采纳评论前的验证工作
        if Comment.objects.filter(topic_id=topic_id, id=comment_id, user=user_info.get('user')).update(
                adoption=True):  # 找到评论,修改采纳状态.
            return JsonResponse({'code': 200, 'message': 'Success'})
        else:
            return JsonResponse({'code': 300, 'message': 'adoption failure'})
    else:
        return JsonResponse({'code': 300, 'message': '无法采纳评论'})

templates/topic/area.html
{% for area in areas %}
    <option value="{{ area.id }}">{{ area.name }}</option>
{% endfor %}

templates/topic/button_group.html
{% load topic_tags %}
<button class="color-aliceblue menu-btn sort-btn sort-up {% is_active topic.id USER.user True %}"
        onclick="topic_loc($(this),{{ topic.id }}, 'True')" data-id="{{ topic.id }}"><span
        class="glyphicon glyphicon-chevron-up color-blue"></span>&nbsp;
    <span class="color-blue-danlan like-count">{{ topic.like }}</span>
</button>
<button class="color-aliceblue menu-btn sort-btn {% is_active topic.id USER.user False %}"
        onclick="topic_loc($(this),{{ topic.id }}, 'False')" data-id="{{ topic.id }}"><span
        class="glyphicon glyphicon-chevron-down color-blue"></span>
</button>

<button class="menu-btn margin-left24 fa-hover"
        onclick="window.location='{% url 'topic:discuss' topic.id %}?anchor=true'"><span><i
        class="fa fa-comment"></i></span>&nbsp;{{ topic | reply_count:'comments' }}&nbsp;评论
</button>
{% ifequal USER.user topic.user.user %}
    <a href="{% url 'topic:modify' %}?topic_id={{ topic.id }}"
       class="menu-btn margin-left24 fa-hover color-black decoration-none padding-3"><i
            class="fa fa-edit"></i>&nbsp;编辑</a>
{% else %}
    <button class="menu-btn margin-left24 fa-hover {% collection_status USER.user topic.id %} collection"
            data-id={{ topic.id }}><span><i
            class="fa fa-star"></i></span>&nbsp;收藏
    </button>
{% endifequal %}
<button class="menu-btn margin-left24 fa-hover share" value="copy{{ topic.id }}"><span><i
        class="fa fa-share-alt"></i></span>&nbsp;分享内容
</button>
<input type="text" value="{{ request.get_host }}{% url 'topic:discuss' topic.id %}"
       id="copy{{ topic.id }}"
       class="hidden-left">
<div class="btn-group dropup">
    {% ifnotequal USER.user topic.user.user %}
        <button class="menu-btn margin-lf5" data-toggle="dropdown"><span><i
                class="fa fa-ellipsis-h"></i></span></button>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">不感兴趣</a></li>
            <li><a href="#">举报内容</a></li>
        </ul>
    {% endifnotequal %}
</div>

templates/topic/discuss.html
{% extends 'base.html' %}
{% load topic_tags %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <script src="{% static 'tinymce/comment.js' %}"></script>
    <script src="{% static 'js/topic/discuss.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/topic/discuss.css' %}">
{% endblock %}
{% block body %}
    <input type="text" id="topic" hidden value="{{ topic.id }}">
    <input type="text" hidden value="{{ csrf_token }}" id="cs_token">
    <div class="content_container">
        <div style="width: 65%" class="background-white shadow">
            <h3 class="padding-lr-25px">{{ topic.title }}</h3>
            <div class="trait padding-lr-25px">
                <div class="width-340">
                    {% if topic.tags.all %}
                        {% for t in topic.tags.all %}
                            <a href="{% url 'topic:search_topic' %}?tag={{ t.tag_id.name }}"
                               class="tag-a">{% if t.tag_id.icon != '/static/img/tag/default.png' %}
                                <img src="{{ t.tag_id.icon }}" alt="">
                            {% endif %}{{ t.tag_id.name }}</a>
                        {% endfor %}
                    {% endif %}
                    {% if USER.level >= 11 %}
                        <button class="menu-btn margin-left24 fa-hover"><span><i class="fa fa-plus"></i></span>&nbsp;新增标签
                        </button>
                    {% endif %}
                </div>
                <span class="float-right margin-left-75"><span class="user_name margin-lf5">
                        <a href="{% url 'user:user_index' topic.user.nickname %}" class="nickname"><img
                                src="/{{ topic.user.avatar }}" alt=""
                                class="content_user_avatar"> {{ topic.user.nickname }}</a>
                </span>
                    <span class="margin-lf5 color-gray">{{ topic.create_time | date:'Y-m-d' }}</span>
                </span>
            </div>
            <div class="texts padding-lr-25px">
                {{ topic.content | safe }}
                <div class="margin-bottom-10 margin-top-10">
                    {% include 'topic/button_group.html' %}
                </div>
            </div>
            <div class="comment">
                <div class="comment-waichen">
                    {% for foo in comments %}
                        {% if foo.status and not foo.reply_obj_id %}
                            <div class="comment-body">
                                <div class="padding-tb10-lr15">
                                <span>
                                    <div class="margin-bottom-10">
                                        <img src="/{{ foo.user.avatar }}" alt="{{ foo.user.nickname }}"
                                             class="comment_avatar"
                                             style="display: inline-block">
                                        <span class="font-bold">{{ foo.user.nickname }}</span>
                                        <span class="margin-lf5 color-gray float-right">
                                            {{ foo.time | date:'Y-m-d' }}
                                            {% if topic.adoption_status.id == foo.id %}
                                            <span class="badge background-green">被采纳</span>
                                            {% endif %}
                                        </span>
                                    </div>
                                    <div>{{ foo.content |safe }}</div>
                                </span>
                                    <div style="display: flex" class="margin-bottom-10">
                                        <button href=""
                                                class="menu-btn color-gray1 like {% comment_loc foo.id USER.user True %}"
                                                data-id="{{ foo.id }}"><i
                                                class="fa fa-thumbs-o-up"></i>&nbsp;
                                            <span>{% comment_loc_count foo.id %}</span>
                                        </button>
                                        <div class="comment_menu_other">
                                            <button data-target="#comment-{{ foo.id }}" data-toggle="collapse"
                                                    data-id="{{ foo.id }}"
                                                    class="menu-btn color-gray1 margin-left24 fa-hover reply-btn"><i
                                                    class="fa fa-reply"></i>&nbsp;回复{{ foo | reply_count:'reply' }}
                                            </button>
                                            <button class="menu-btn color-gray1 margin-left24 fa-hover contra"
                                                    data-id="{{ foo.id }}"><i
                                                    class="fa fa-thumbs-o-down"></i>&nbsp;<span>{% comment_loc foo.id USER.user False %}</span>
                                            </button>
                                            <button class="menu-btn color-gray1 margin-left24 fa-hover"><i
                                                    class="fa fa-flag"></i>&nbsp;举报
                                            </button>
                                            {% if USER.user == topic.user.user and topic.adoption_status is None %}
                                                <button class="menu-btn color-gray1 margin-left24 fa-hover adoption-btn"
                                                        data-id="{{ foo.id }}"><i
                                                        class="fa fa-check"></i>&nbsp;采纳
                                                </button>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row collapse" id="comment-{{ foo.id }}">
                                        <div class="margin-left24 margin-r15 reply-div"><span></span><span></span></div>
                                        <div id="reply-{{ foo.id }}">
                                            {% if USER %}
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="reply{{ foo.id }}">
                                                </div>
                                                <div class="col-sm-2">
                                                    <button class="font-bold color-white comment-btn submitReply"
                                                            value="{{ foo.id }}">提交
                                                    </button>
                                                </div>
                                            {% else %}
                                                <span class="padding-lr-25px margin-left35p">回复评论需要你先登入.</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% include 'pagination.html' with topics=comments %}
            <div class="text-box">
                <form action="{% url 'topic:comment' topic.id %}" method="post">
                    {% csrf_token %}
                    <textarea name="comment" id="#textarea" cols="30" rows="10"></textarea>
                    <button class="comment-btn font-bold color-white">评论</button>
                </form>
            </div>
        </div>
        <div style="height: 200px;width: 34%;border: solid 1px" class="background-white">

        </div>
    </div>
    <span id="anchor"></span>
{% endblock %}

templates/topic/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <link rel="stylesheet" href="/static/css/topic/code.css">
{% endblock %}
{% block body %}
    <div class="container ">
        <div class="col-sm-8 ">
            <div class="margin-bottom-10 background-white margin-top-10">
                {% if tag %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" class="decoration-none"
                                   href="#tag">
                                    <img src="{{ tag.icon }}" alt="icon">
                                    {{ tag.name }}
                                </a>
                            </h4>
                        </div>
                        <div id="tag" class="panel-collapse collapse">
                            <div class="panel-body">
                                {{ tag.description }}
                            </div>
                        </div>
                    </div>
                {% endif %}
                <ul class="nav nav-tabs topic_sort">
                    <li class="{% if request.GET.sort == 'hot' %}active{% endif %}">
                        <a href="?{% if args %}{{ args }}&{% endif %}sort=hot">热门话题</a></li>
                    <li class="{% if request.GET.sort == 'now' %}active{% endif %}"><a
                            href="?{% if args %}{{ args }}&{% endif %}sort=now">最新话题</a></li>
                    <li class="{% if request.GET.sort == 'over' %}active{% endif %}"><a
                            href="?{% if args %}{{ args }}&{% endif %}sort=over">完结话题</a></li>
                </ul>
            </div>
            {% for topic in topics %}
                {% include 'topic/topic_list.html' %}
            {% endfor %}
            {% include 'pagination.html' %}
        </div>
        <div class="col-sm-4" style="border: solid;height: 400px;">

        </div>
    </div>
{% endblock %}

templates/topic/modify.html
{% extends 'base.html' %}
{% load topic_tags %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}{% endblock %}
{% block body %}
    <form action="{% url 'topic:modify' %}" method="post">
        <input type="text" hidden name="topic_id" value="{{ topic.id }}">
        {% csrf_token %}
        <div class="modal-header">
            <div class="col-sm-6 padding-left-0">
                <input type="text" class="form-control" placeholder="话题标题" name="title" value="{{ topic.title }}">
            </div>
            <div class="col-sm-2 padding-left-0">
                <select name="area" class="form-control">
                    {% get_area topic.area_id.id %}
                </select>
            </div>
            <div class="col-sm-3 padding-left-0">
                <input type="text" placeholder="话题标签,多标签以空格隔开." class="form-control"
                       name="tags" value="{% for tag in topic.tags.all %}{{ tag.tag_id.name }}&nbsp;{% endfor %}">
            </div>
        </div>
        <div class="modal-body">
            <h3 class="margin-top-0">话题内容:</h3>
            <textarea name="content" id="textarea_modify" cols="30" rows="10"
                      class="textarea">{{ topic.content }}</textarea>
        </div>
        <div class="modal-footer">
            <button>提交</button>
        </div>
    </form>
{% endblock %}

templates/topic/topic_list.html
{% load topic_tags %}
<div class="margin-bottom-10 topic-container background-white">
    <div>
        <div class="tags-div" style="min-height: 20px">
            {% if topic.tags.all %}
                {% for t in topic.tags.all %}
                    <a href="{% url 'topic:search_topic' %}?tag={{ t.tag_id.name }}"
                       class="tag-a">{% if t.tag_id.icon != '/static/img/tag/default.png' %}
                        <img src="{{ t.tag_id.icon }}" alt="">
                    {% endif %}{{ t.tag_id.name }}</a>
                {% endfor %}
            {% endif %}
            <span class="float-right color-gray">{{ topic.create_time | date:'Y-m-d' }}</span>
        </div>
        {% if home_page %}
            {% if collect %}
                <div class="display-flex margin-bottom-10 right">
                    <div><a href="{% url 'user:user_index' topic.user.nickname %}"><img
                            src="/{{ topic.user.avatar }}" alt="user_avatar" class="user_avatar"></a>&nbsp;
                    </div>
                    <div class="display-flex">
                        <div><a href="{% url 'user:user_index' topic.user.nickname %}"
                                class="nickname">{{ topic.user.nickname }}&nbsp;</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% else %}
            <div class="display-flex margin-bottom-10 right">
                <div><a href="{% url 'user:user_index' topic.user.nickname %}"><img
                        src="/{{ topic.user.avatar }}" alt="user_avatar" class="user_avatar"></a>&nbsp;
                </div>
                <div class="display-flex">
                    <div><a href="{% url 'user:user_index' topic.user.nickname %}"
                            class="nickname">{{ topic.user.nickname }}&nbsp;</a>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="font-bold font-size-18 line-height-15">
            <a href="{% url 'topic:discuss' topic.id %}"
               class="decoration-none color-black">{{ topic.title }}</a>
        </div>
    </div>

    <div class="margin-bottom-10 margin-top-10 text-body"
         onclick="window.location='{% url 'topic:discuss' topic.id %}'">
        <div class="thumbnails float-left">{{ topic.content | get_img:'img'  |safe }}</div>
        <div class="{{ topic.content | get_img:None }} part-visible padding-left-5px">{{ topic.content | get_label:'pre p' | out_img | safe }}</div>
    </div>
    <div>
        {% include 'topic/button_group.html' %}
    </div>
</div>