audit/urls.py
from django.urls import path
from audit.views import index, topic, process, comment, tag, tag_modify, audit_message, user, audit_user

app_name = 'audit'

urlpatterns = [
    path('index/', view=index, name='index'),
    #  视图页
    path('topic/', view=topic, name='topic'),
    path('comment/', view=comment, name='comment'),
    path('tag/', view=tag, name='tag'),
    path('user/', view=user, name='user'),
    #  功能视图
    path('process/', view=process, name='process'),
    path('tag_modify/', view=tag_modify, name='tag_modify'),
    path('audit_message/', view=audit_message, name='message'),
    path('audit_user/', view=audit_user, name='audit_user')
]

topic/urls.py
from django.urls import path
from topic.views import release, topic_index, discuss, comment, get_reply, collection, comment_loc, topic_loc, \
    search_topic, modify, adoption

app_name = 'topic'

urlpatterns = [
    path('release/', view=release, name='release'),
    path('modify/', view=modify, name='modify'),
    path('area/<area>/', view=topic_index, name='topic_index'),
    path('search/', view=search_topic, name='search_topic'),
    path('discuss/<topic_id>/', view=discuss, name='discuss'),
    path('comment/<topic_id>/add', view=comment, name='comment'),
    path('get_reply/', view=get_reply, name='get_reply'),
    path('collection/', view=collection, name='collection'),
    path('comment_loc/', view=comment_loc, name='comment_loc'),
    path('topic_loc/', view=topic_loc, name='topic_loc'),
    path('adoption/', view=adoption, name='adoption')
]

user/urls.py
from django.urls import path
from user.views import registered, login, logout, user_index, leave_message, mailbox, get_message, del_message, \
    settings, bind_email, modify_password, application_reset_password, reset_password, modify_personal_information

app_name = 'user'
urlpatterns = [
    path("registered/", view=registered, name='registered'),
    path('login/', view=login, name='login'),
    path('logout/', view=logout, name='logout'),
    path('user_index/<user_nickname>/', view=user_index, name='user_index'),
    path('leave_message/', view=leave_message, name='leave_message'),
    path('mailbox/', view=mailbox, name='mailbox'),
    path('get_message/', view=get_message, name='get_message'),
    path('del_message/', view=del_message, name='del_message'),
    path('settings/', view=settings, name='settings'),
    path('settings/bind_email/', view=bind_email, name='bind_email'),
    path('settings/modify_password/', view=modify_password, name='modify_password'),
    path('settings/modify_personal_information/', view=modify_personal_information, name='modify_personal_information'),
    path('reset_password/application', view=application_reset_password, name='application_reset_password'),
    path('reset_password/<code>', view=reset_password, name='reset_password')
]

xuetang/urls.py
from django.contrib import admin
from django.urls import path, include
from xuetang.views import home, upload, get_verification, send_code

urlpatterns = [
    path("user/", include("user.urls")),
    path('topic/', include('topic.urls')),
    path('audit/', include('audit.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', view=home, name="home"),
    path('home/', view=home, name="home"),
    path('upload/', view=upload, name='upload'),
    path("get_verification/", view=get_verification, name='get_verification'),
    path('send_code/', view=send_code, name='send_code')
]

audit/models.py
from django.db import models

# Create your models here.

topic/models.py
from django.db import models

# Create your models here.

audit/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse, HttpResponseRedirect
from topic.models.model import Topic, Comment, Tag
from user.models.model import Message, User
from xuetang.plug_ins import save_img


# Create your views here.

def index(request):
    """审核管理首页,
    呈现各类待审核项目条数
    """
    content = {
        'title': '审核管理',
    }
    return render(request, template_name='audit/index.html', context=content)


"""用户审核"""


def user(request):
    """用户审核页"""

    content = {
        'title': '用户审核',
        'users': User.objects.filter(status=False).order_by('-create_time').all()
    }

    return render(request, template_name='audit/user.html', context=content)


def audit_user(request) -> JsonResponse:
    """用户审核通过处理"""
    user_id = request.POST.get('user_id')
    try:
        User.objects.filter(id=user_id, status=False).update(status=True)
    except BaseException as err:
        print(err)
    return JsonResponse({'status': 'ok'})


"""标签审核"""


def tag(request):
    """标签审核页"""

    content = {
        'title': '标签管理',
        'tagsF': Tag.objects.filter(status=False).order_by('-create_time').all(),  # 未审核
        'tagsT': Tag.objects.filter(status=True).all()  # 已审核
    }
    return render(request, template_name='audit/tag.html', context=content)


def tag_modify(request):
    """修改标签图标与描述,名称不允许修改.
    :return: 回到标签审核界面
    """

    tag_id = request.POST.get('tag_id')
    t = Tag.objects.filter(id=tag_id).first()
    url = request.POST.get('icon_url')
    description = request.POST.get('description')
    if description != '':
        # 描述有传值才更新数据
        t.description = description
    # url优先等级更高
    if url != '':
        if url == 'default':
            t.icon = '/static/img/tag/default.png'
        else:
            t.icon = url
    else:
        file = request.FILES.get('icon')
        if file:
            url = save_img(file, folder='tag')
            t.icon = url['src']
    t.save()
    return HttpResponseRedirect(reverse('audit:tag'))


"""话题与评论审核"""


def topic(request):
    """话题审核页"""

    content = {
        'title': '话题审核',
        'topics': Topic.objects.filter(status=False, delete_status=False).all()
    }
    return render(request, template_name='audit/topic.html', context=content)


def comment(request):
    """评论审核页"""

    content = {
        'title': '评论审核',
        'comments': Comment.objects.filter(status=False, delete_status=False).order_by('-time').all()
    }
    return render(request, template_name='audit/comment.html', context=content)


def process(request) -> JsonResponse:  # process:处理
    """处理话题与评论审核的请求视图"""

    request_get = request.GET.get
    #  main_id:表主键id model:模型对象 process_type:操作字段,(status,delete_status,audit_message). message:留言信息
    main_id = request_get('main_id')
    model = request_get('model')
    process_type = request_get('type')
    value = request_get('value')
    # 模型通过前台传回的model选择
    models = {
        'topic': Topic,
        'comment': Comment,
        'tag': Tag,
    }
    # 操作字段的值,通过前台传回的value选择.
    values = {
        'False': False,
        'True': True,
    }
    # 收集操作所需参数后,对数据库进行操作.
    obj = models[model].objects.filter(id=main_id).first()
    setattr(obj, process_type, values[value])
    obj.save()
    # 最终在前台提示 未完成.
    return JsonResponse({'status': 'ok'})


def audit_message(request) -> JsonResponse:
    """审核留言
    用户帐号不应该暴露在前台,所以to_user_id通过对象id查询到User.user再存入Message."""

    request_post = request.POST.get
    kw = {
        'types': request_post('types'),
        'types_id': request_post('type_id'),
        'to_user_id': User.objects.filter(id=request_post('to_user')).first().user,
        'user_id': request.session.get('user')['user'],
        'content': request_post('content')
    }
    m = Message(**kw)
    m.save()
    return JsonResponse({'status:': 'ok'})

topic/views.py
import operator
from functools import reduce
from django.shortcuts import render, HttpResponseRedirect, reverse, Http404
from django.http import JsonResponse
from topic.plug_ins import sort_out_tag, save_topic, get_topic, modify_loc, get_paginator, adoption_review
from .models import Area, Topic, Comment, Collection, Tag
from django.db.models import Q
from xuetang.plug_ins import get_user


# Create your views here.


def release(request):
    """发布话题
    :param request:
    :return:返回发布话题所在页面,未完成.返回发布结果信息.未完成
    """
    tags = request.POST.get('tags').split()

    # 保存话题
    topic = save_topic(request)

    if tags:
        # 如果有标签,创建标签,简历标签与话题关系
        sort_out_tag(topic, tags)
    return HttpResponseRedirect(reverse('topic:topic_index', args=[topic.area_id.path_name]))


def modify(request):
    """话题编辑页面与处理编辑内容
    :param request:
    :return: GET返回编辑页面,POST返回话题讨论页.
    """
    if request.method == 'GET':
        topic_id = request.GET.get('topic_id')
        topic = Topic.objects.filter(id=topic_id).first()
        content = {
            'title': '编辑话题',
            'topic': topic
        }
        return render(request, template_name='topic/modify.html', context=content)
    else:
        tags = request.POST.get('tags').split()
        topic_id = request.POST.get('topic_id')
        topic = Topic.objects.filter(id=topic_id).first()
        topic = save_topic(request, topic)
        sort_out_tag(topic, tags)
        return HttpResponseRedirect(reverse('topic:topic_index', args=[topic.area_id.path_name]))


def topic_index(request, area):
    """话题分区视图.
    :param request:
    :param area: 分区代号,作为筛选话题的主要条件之一.与前台sort分类标识
    :return: 话题列表
    """
    # 获取分区话题
    topics = get_topic(request, {'area_id__path_name': area})
    # 获取分区名,返回给前台title
    area_name = Area.objects.filter(path_name=area).first().name
    # page:请求页数 paginator:分页对象 page_list:处理过后的分页数
    page = int(request.GET.get('page', 1))
    topic, paginator, page_list = get_paginator(page, topics)
    content = {
        'title': area_name,
        'args': 'sort=' + request.GET.get('sort', ''),
        'area': area,
        'page': page,
        'topics': topic,
        'paginator': paginator,
        'page_list': page_list,
        'topic': True
    }
    return render(request, template_name='topic/index.html', context=content)


def search_topic(request):
    """搜索视图
    不支持tag与question双参数同时搜索.
    收集tag\question\page url参数,
    args为当前搜索内容记录,在分页导航中传入args内容.
    :param request:
    :return:
    """
    # page:请求页码,tag:标签名,question:问题内容
    page = int(request.GET.get('page', 1))
    tag = request.GET.get('tag')
    tag = Tag.objects.filter(name=tag).first()
    question = request.GET.get('question')
    # 不支持双参数同时搜索,优先搜索tag标签
    if tag:
        # topics: 获取话题中,外键id等于tag,并且状态为true的所有话题集合
        topics = get_topic(request, {'tags__tag_id': tag.id, 'status': True})

        # 将topics交给get_paginator处理获得指定页数,指定每页内容的topic 返回前台呈现
        topic, paginator, page_list = get_paginator(page=page, topics=topics, per_page=20)

        # args:url参数,维持分页功能.
        args = 'tag=' + tag.name
        title = tag.name

    elif question:
        # 查找关键词中包含的第一个标签,供前台呈现.
        for i in question.split():
            tag = Tag.objects.filter(name=i).first()
            # 查找第一个,找到即不再继续.
            if tag:
                break

        # Q_obj:多参数模糊查询.底层机制完全不知道.待解决.
        Q_obj = reduce(operator.or_,
                       ([Q(**{'title__icontains': i}) | Q(**{'content__icontains': i}) for i in question.split()]))

        # 获取话题集合
        topics = get_topic(request, Q_obj=Q_obj)

        # 获取分页相关数据
        topic, paginator, page_list = get_paginator(page=page, topics=topics, per_page=20)

        # args:url参数,维持搜索分页功能.
        args = 'question=' + question
        title = question
    else:
        return Http404
    content = {
        'title': title,
        'page': page,
        'topics': topic,
        'paginator': paginator,
        'page_list': page_list,
        'args': args,
        'tag': tag
    }
    return render(request, template_name='topic/index.html', context=content)


def discuss(request, topic_id):
    """话题讨论页面
    :param request:
    :param topic_id: 话题id
    :return: 返回话题内容页面
    """
    page = int(request.GET.get('page', 1))
    topic = Topic.status_true.filter(id=topic_id).first()

    comments = topic.comments.filter(status=True, reply_obj_id=None, adoption=False).all()
    comments, paginator, page_list = get_paginator(page, comments, per_page=20)

    if page == 1:  # 第一页 需要展示被采纳的评论
        adoption_ = topic.comments.filter(status=True, adoption=True).first()  # 查找被采纳的评论
        if adoption_:  # 当被采纳的评论存在时
            comments = list(comments)  # 列表化评论集合
            comments.insert(0, adoption_)  # 插入评论

    contents = {
        'title': topic.title,
        'area': topic.area_id.path_name,
        'topic': topic,
        'comments': comments,
        'paginator': paginator,
        'page_list': page_list,
        'page': page
    }
    return render(request, template_name='topic/discuss.html', context=contents)


def comment(request, topic_id):
    """处理评论请求
    :param request:
    :param topic_id: 话题id,定位评论与话题关系
    :return: 当请求属于reply回复评论时,返回状态信息等...当请求属于评论时,跳转至话题页面,并携带message信息.
    """
    # 获取user判断评论有效性 obj判断是否为回复
    user = get_user(request)
    content = request.POST.get('comment', None)
    obj = request.POST.get('reply', None)
    kwargs = {'reply_obj_id': obj} if obj else {}
    # 以url参数message=xxx的方式传递给给前台的消息反馈,具体消息在前台js文件内.
    message = '?'
    if user:
        # 当用户帐号未激活时,将评论状态改为待审核,并做出相应提示.
        if user.level == 0:
            kwargs.update({'status': False})
            message += 'message=comment-level'
        comment = Comment(user_id=user.user, topic_id_id=topic_id, content=content, **kwargs)
        comment.save()
    else:
        # 获取游客ip message提示评论需要审核
        ip = request.META['REMOTE_ADDR']
        message += "message=comment-audit"
        comment = Comment(user_id='AdminAudit', status=False, topic_id_id=topic_id, content=content, ip=ip, **kwargs)
        comment.save()
    # 如果有reply对象,请求则为ajax请求,返回前台所需的反馈信息.
    if obj:
        # reply回复功能,不允许未登入用户回复,
        return JsonResponse({'status': 'ok', 'user': comment.user.nickname, 'content': comment.content})
    else:
        return HttpResponseRedirect(reverse('topic:discuss', args=[topic_id]) + message)


def get_reply(request):
    """获取指定评论对象,得到回复数据,以json格式返回给前台,由前台渲染呈现.
    :param request:
    :return: 返回状态码,replys:回复集合. replys是由n个{user:xx, content:xx}组成的列表
    """
    reply = int(request.GET.get('reply'))

    # 得到全部指向评论id的状态为true的回复
    comments = Comment.objects.filter(status=True, reply_obj=reply).all()

    replys = []
    # 如果comments不为None, 循环comments 生成{user:xx, content:xx}格式的字典表,追加进replys,供前台呈现.
    if comments:
        for i in comments:
            replys.append({
                'user': i.user.nickname,
                'content': i.content
            })
    return JsonResponse({'status': 'ok', 'replys': replys})


def collection(request):
    """收藏话题请求\处理,视图.
    如果用户当前未登录,直接返回failure状态码,如果已登录,再继续做判断.
    :param request:
    :return: 状态码与相应提示信息通知
    """
    user = get_user(request)
    if user:
        topic = request.GET.get('topic')
        c = Collection.objects.filter(topic_id_id=topic, user=user).first()
        if c:
            # 用户已收藏此话题,当前请求判断为取消收藏.选择删除收藏关系
            c.delete()
            return JsonResponse({'status': 'success', 'message': 'cancel-collection'})
        else:
            # 用户未收藏此话题,建立收藏关系
            c = Collection(topic_id_id=topic, user=user)
            c.save()
            return JsonResponse({'status': 'success', 'message': 'collection-success'})
    else:
        return JsonResponse({'status': 'failure', 'message': 'collection-failure'})


def comment_loc(request):
    """comment like or contra 关系处理视图
    :param request:
    :return:
    """
    result = modify_loc(request, 'comment')
    key_id = result.pop('key_field', None)
    # 如果有key_id 表示关系处理正常,返回相关信息到前台.
    if key_id:
        return JsonResponse(result)
    else:
        return Http404


def topic_loc(request):
    """话题like or contra 关系处理视图
    从modify_loc获取关系 +- 动作结果,修改话题相关字段值
    :param request: 成功返回关系结果,否则返回404状态,前端不执行后续js操作
    :return:
    """
    result = modify_loc(request, 'topic')
    key_id = result.pop('key_field', None)

    # 如果有key_id 表示关系处理正常,修改话题相关字段值.
    if key_id:
        topic = Topic.objects.filter(pk=key_id).first()
        topic.like += result.pop('like')  # 这里有bug 在高并发的情况下容易出错.不应该查询再增减而是通过sql直接修改数据
        topic.contra += result.pop('contra')
        topic.save()
        return JsonResponse(result)
    else:
        raise Http404


def adoption(request):
    """采纳评论视图"""
    topic_id = request.POST.get('topic_id')
    comment_id = request.POST.get('comment_id')
    user_info = request.session.get('user')

    try:
        assert user_info, 'user is none'  # 验证用户是否登录
    except AssertionError as err:
        print(err)
        return JsonResponse({'code': 500, 'message': 'You do not have permission'})

    if adoption_review(topic_id=topic_id, user_user=user_info.get('user')):  # 采纳评论前的验证工作
        if Comment.objects.filter(topic_id=topic_id, id=comment_id, user=user_info.get('user')).update(
                adoption=True):  # 找到评论,修改采纳状态.
            return JsonResponse({'code': 200, 'message': 'Success'})
        else:
            return JsonResponse({'code': 300, 'message': 'adoption failure'})
    else:
        return JsonResponse({'code': 300, 'message': '无法采纳评论'})

templates/audit/comment.html
{% extends 'audit/index.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <link rel="stylesheet" href="{% static 'css/audit/comment.css' %}">
{% endblock %}
{% block body %}
    <div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th style="width: 10%">用户</th>
                <th style="width: 4%">类型</th>
                <th style="width: 7%">时间</th>
                <th style="width: 10%">操作</th>
                <th>内容</th>
            </tr>
            </thead>
            <tbody>
            {% if comments %}
                {% for comment in comments %}
                    <tr id="comment{{ comment.id }}">
                        <td>{{ comment.user.nickname }}</td>

                        <td>{% if comment.reply_obj %}回复{% else %}评论{% endif %}</td>
                        <td>{{ comment.time|date:'Y-m-d' }}</td>
                        <td>
                            <button class="btn btn-success audit-btn" data-id="{{ comment.id }}" data-value="True"
                                    data-type="status">
                                审核通过
                            </button>
                            <button class="btn btn-danger audit-btn" data-id="{{ comment.id }}"
                                    data-type="delete_status" data-value="True">
                                删除
                            </button>
                            <button class="btn btn-primary leaveAMessage-btn" data-id="{{ comment.id }}"
                                    data-to_user="{{ comment.user.id }}">留言
                            </button>
                            <input type="text" id="{{ comment.id }}">
                        </td>
                        <td>{{ comment.content|safe }}</td>
                    </tr>
                {% endfor %}

            {% endif %}
            </tbody>
        </table>
    </div>
    <input type="text" hidden value="{{ csrf_token }}" id="csrf_token">
    <script src="{% static 'js/audit/comment.js' %}"></script>
{% endblock %}

templates/audit/index.html
{% load audit_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %} | 学堂</title>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    {% block resources %}{% endblock %}
</head>
<body>
<div>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'audit:index' %}">审核管理</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'audit:topic' %}">话题审核 <span class="badge">{% audit_count 'topic' None %}</span></a>
                    </li>
                    <li><a href="{% url 'audit:comment' %}">评论审核 <span
                            class="badge">{% audit_count 'comment' None %}</span></a></li>
                    <li><a href="{% url 'audit:tag' %}">标签审核 <span
                            class="badge">{% audit_count 'tag' 'delete_status' %}</span></a></li>
                    <li><a href="{% url 'audit:user' %}">用户审核<span class="badge">{% audit_count 'user' 'delete_status' %}</span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            其他
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">无</a></li>
                        </ul>
                    </li>
                    <li><a href="/">返回首页</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% block body %}
    <div>

    </div>
{% endblock %}
</body>
</html>

templates/audit/tag.html
{% extends 'audit/index.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
{% endblock %}
{% block body %}
    <div style="display: flex">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion"
                       href="#false">
                        待审核标签
                    </a>
                </h4>
            </div>
            <div id="false" class="panel-collapse collapse in">
                <div class="panel-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>图标</th>
                            <th>标签名</th>
                            <th>描述</th>
                            <th>创建时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if tagsF %}
                            {% for tag in tagsF %}
                                <tr>
                                    <td><img src="{{ tag.icon }}" alt="{{ tag.name }}"></td>
                                    <td>{{ tag.name }}</td>
                                    <td>{{ tag.description }}</td>
                                    <td>{{ tag.create_time|date:'Y-m-d' }}</td>
                                    <td>
                                        <button class="btn btn-success audit-btn" data-id="{{ tag.id }}"
                                                data-value="True" data-type="status"> 审核通过
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion"
                       href="#true">
                        已审核标签
                    </a>
                </h4>
            </div>
            <div id="true" class="panel-collapse collapse in">
                <div class="panel-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>图标</th>
                            <th>标签名</th>
                            <th>描述</th>
                            <th>关注</th>
                            <th>创建时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if tagsT %}
                            {% for tag in tagsT %}
                                <tr>
                                    <td>
                                        <img src="{{ tag.icon }}" alt="{{ tag.name }}">
                                    </td>
                                    <td>{{ tag.name }}</td>
                                    <td>
                                        {{ tag.description }}
                                    </td>
                                    <td>{{ tag.attention }}</td>
                                    <td>{{ tag.create_time|date:'Y-m-d' }}</td>
                                    <td>
                                        <button class="btn btn-success audit-btn" data-id="{{ tag.id }}"
                                                data-value="False" data-type="status"> 关闭
                                        </button>
                                        <button class="btn btn-primary modify" data-id="{{ tag.id }}"
                                                data-name="{{ tag.name }}">修改
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div style="position: absolute;left: -1000px;width: 100px" id="form-div">
            <form action="{% url 'audit:tag_modify' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name="tag_id" id="tag_id" hidden>
                <span>标签名:<span id="tag_name" style="font-weight: bold"></span></span><br>
                <label for="icon">图标<input type="file" id="icon" name="icon">
                    <input type="text" placeholder="使用url地址,默认值:default" name="icon_url">
                </label>
                <label for="description">描述 <textarea name="description" id="description" cols="30" rows="3"></textarea>
                </label>
                <input type="submit" value="提交修改" class="btn btn-primary">
            </form>
        </div>
    </div>
    <script src="{% static 'js/audit/tag.js' %}"></script>
{% endblock %}

templates/audit/topic.html
{% extends 'audit/index.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <link rel="stylesheet" href="{% static 'css/audit/topic.css' %}">
{% endblock %}
{% block body %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="10%">用户</th>
            <th width="10%">标题</th>
            <th width="60%">内容</th>
            <th width="7%">时间</th>
            <th width="10%">操作</th>
        </tr>
        </thead>
        <tbody>
        {% if topics %}
            {% for topic in topics %}
                <tr id="topic{{ topic.id }}">
                    <td>{{ topic.user.nickname }}</td>
                    <td>{{ topic.title }}</td>
                    <td><div style="overflow-y: auto; max-height: 200px">
                        {{ topic.content |safe }}
                    </div></td>
                    <td>{{ topic.create_time |date:'Y-m-d' }}</td>
                    <td>
                        <button class="btn btn-success audit-btn" data-id="{{ topic.id }}" data-value="True" data-type="status"> 审核通过
                        </button>
                        <button class="btn btn-danger audit-btn" data-id="{{ topic.id }}" data-value="True" data-type="delete_status">
                            删除
                        </button>
                            <button class="btn btn-primary leaveAMessage-btn" data-id="{{ topic.id }}"
                                    data-to_user="{{ topic.user.id }}">
                                留言建议
                            </button>
                            <input type="text" id="{{ topic.id }}" placeholder="{{ topic.audit_message }}">
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
    <input type="text" hidden value="{{ csrf_token }}" id="csrf_token">
    <script src="{% static 'js/audit/topic.js' %}"></script>
{% endblock %}

templates/audit/user.html
{% extends 'audit/index.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <link rel="stylesheet" href="{% static 'css/audit/comment.css' %}">
{% endblock %}
{% block body %}
    <div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th style="width: 10%">用户</th>
                <th style="width: 7%">时间</th>
                <th style="width: 10%">操作</th>
                <th>内容</th>
            </tr>
            </thead>
            <tbody>
            {% if users %}
                {% for user in users %}
                    <tr id="comment{{ user.id }}">
                        <td>{{ user.nickname }}</td>

                        <td>{{ user.create_time|date:'Y-m-d' }}</td>
                        <td>
                            <button class="btn btn-success audit-btn" data-id="{{ user.id }}" data-value="True"
                                    data-type="status">
                                审核通过
                            </button>
                            <button class="btn btn-primary leaveAMessage-btn" data-id="{{ user.id }}"
                                    data-to_user="{{ user.id }}">留言
                            </button>
                            <input type="text" id="{{ user.id }}">
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
    <input type="text" hidden value="{{ csrf_token }}" id="csrf_token">
    <script src="{% static 'js/audit/user.js' %}"></script>
{% endblock %}