user/urls.py
from django.urls import path
from user.views import registered, login, logout, user_index, leave_message, mailbox, get_message, del_message, \
    settings, bind_email, modify_password, application_reset_password, reset_password, modify_personal_information

app_name = 'user'
urlpatterns = [
    path("registered/", view=registered, name='registered'),
    path('login/', view=login, name='login'),
    path('logout/', view=logout, name='logout'),
    path('user_index/<user_nickname>/', view=user_index, name='user_index'),
    path('leave_message/', view=leave_message, name='leave_message'),
    path('mailbox/', view=mailbox, name='mailbox'),
    path('get_message/', view=get_message, name='get_message'),
    path('del_message/', view=del_message, name='del_message'),
    path('settings/', view=settings, name='settings'),
    path('settings/bind_email/', view=bind_email, name='bind_email'),
    path('settings/modify_password/', view=modify_password, name='modify_password'),
    path('settings/modify_personal_information/', view=modify_personal_information, name='modify_personal_information'),
    path('reset_password/application', view=application_reset_password, name='application_reset_password'),
    path('reset_password/<code>', view=reset_password, name='reset_password')
]

xuetang/urls.py
from django.contrib import admin
from django.urls import path, include
from xuetang.views import home, upload, get_verification, send_code

urlpatterns = [
    path("user/", include("user.urls")),
    path('topic/', include('topic.urls')),
    path('audit/', include('audit.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', view=home, name="home"),
    path('home/', view=home, name="home"),
    path('upload/', view=upload, name='upload'),
    path("get_verification/", view=get_verification, name='get_verification'),
    path('send_code/', view=send_code, name='send_code')
]

user/models/form.py
from django import forms
from django.core import validators


class UserForm(forms.Form):
    user = forms.CharField(label='登入账号', max_length=20, min_length=1,
                           validators=[validators.RegexValidator(regex='^[a-zA-Z0-9_\w]+$', message='包含非法字符')],
                           error_messages={'max_length': '登入账号不能超过20个字符'})
    nickname = forms.CharField(label='昵称', max_length=20, min_length=1, error_messages={'required': '昵称必须填写'},
                               validators=[validators.RegexValidator(regex='^[a-zA-Z0-9_\w]+$', message='包含非法字符')])
    password = forms.CharField(label='密码', min_length=1, max_length=48)
    email = forms.EmailField(label='邮箱', required=False)


class LoginForm(forms.Form):
    user = forms.CharField(label='登入账号', max_length=20, min_length=1,
                           validators=[validators.RegexValidator(regex='^[a-zA-Z0-9_\w]+$', message='包含非法字符')],
                           error_messages={'max_length': '帐号最大长度为20个字符!'})
    password = forms.CharField(label='密码', min_length=1, max_length=48)

user/views.py
from django.shortcuts import render, reverse, Http404, HttpResponseRedirect
from django.http import JsonResponse
from django.db.models import Count
from xuetang.config import DOMAIN_NAME
from xuetang.views import get_verification
from xuetang.plug_ins import ip_defense, get_user, judgment_code, send_mail, generate_code, save_img
from .plug_ins import verify_login, verification_field, write_cookie, is_self
from topic.plug_ins import get_paginator
from .models.form import UserForm, LoginForm
from .models.model import Defense, User, Cookie, Message
from topic.models.model import Topic


# Create your views here.

def login(request):
    """接收登录请求,验证.
    登录成功:将用户信息写入session.用户勾选remember则生成cookie:sid信息返回前台,在前台完成cookie写入.失败:通知前台,登录失败.
    :return:status,url,sid,error.
    """
    user = request.POST.get('user', None)
    password = request.POST.get('password', None)
    remember = request.POST.get('remember', None)
    href = request.POST.get('href', None)

    f = LoginForm({'user': user, 'password': password})
    response = {'status': 'no', 'error': '帐号密码错误'}
    if f.is_valid():
        if verify_login(request, user, password):
            response.update({
                'status': 'ok',
                'url': href
            })
            if remember is not None and remember == 'true':
                response.update({'sid': write_cookie(user)})
    return JsonResponse(response)


def logout(request):
    """用户登出,删除session,删除cookie
    :return: 跳转到不需要登录状态的首页
    """
    user = request.session.get('user', None)
    if user:
        request.session.pop('user')
        c = Cookie.objects.filter(user=user['user']).first()
        if c:
            c.delete()
    return HttpResponseRedirect(reverse('home'))


@ip_defense(refresh_hour=24, frequency=30)
def registered(request):
    """验证注册表单,不符合条件则收集错误信息,反馈给前台用户.
    每次注册,修改ip_defense各项数值.超过一定数值,则不再继续处理注册请求.
    :return: 注册成功,更新session,跳转页面. 注册失败,更新验证码,返回json数据.
    """

    # error存储所有错误信息,以{field:message}结构存储. respond 存储反馈信息:status,url,src,interval,error....
    error = {}
    respond = {}

    # 获取表单信息 弹出多余的cs_token 获取form对象,以便写入数据库. verification:获取验证码结果. defense:获取ip记录
    form = request.POST.dict()
    form.pop('csrfmiddlewaretoken')
    f = UserForm(form)
    verification = form.pop('verification', None) == request.session['code']
    defense = Defense.objects.filter(user_ip=request.META['REMOTE_ADDR'], func_name='registered').first()

    # 遍历所有字段,发现任何字段非唯一,将该字段错误信息写入error.最终返回验证结果unique
    unique = verification_field(User, ['user', 'nickname', 'email'], form, error)

    if f.is_valid() and verification and unique:
        # 修改defense,在防御有效期后,才可再次注册帐号.
        defense.status = False
        defense.save()
        # 响应前台,通知注册结果.
        respond['status'] = 'ok'
        respond['url'] = reverse('home')
        # ?未完成
        # 将数据存入数据库,并且修改登录状态session
        if not len(form['email']):
            form['email'] = None
        user = User(**form)
        user.registered()

    else:
        # frequency:注册次数 interval:间隔时间(单位:second)
        defense.frequency += 1
        defense.interval += 1
        defense.save()

        # 更新验证码
        get_verification(request)

        # 响应前台,通知注册结果,更新验证码src
        respond['status'] = 'no'
        respond['src'] = request.session['file_path']

        # forms.errors返回的数据结构复杂,处理后以{field:message}结构返回前台,并告知前台等待间隔时间.
        for i in f.errors.as_data().items():
            error.update({i[0]: i[1][0].messages[0]})
        respond['error'] = error
        respond['interval'] = defense.interval
        if not verification:
            respond['error'].update({'verification': '验证码错误'})
    return JsonResponse(respond)


def user_index(request, user_nickname):
    """用户个人主页
    :param request:
    :param user_nickname:用户昵称
    """
    # user:访问的是user的主页
    user = User.objects.filter(nickname=user_nickname).first()
    # collect:请求查看收藏夹
    # 以collect请求与is_self共同判断是否展示收藏夹.
    collect = eval(request.GET.get('collect', 'False'))
    self = is_self(request, user)
    if collect and self:
        topics = [i.topic_id for i in user.collections.all()]
    else:
        # 如果不为本人浏览主页
        topics = Topic.objects.filter(user_id=user.user, status=True, delete_status=False).all()
        collect = False
    page = int(request.GET.get('page', 1))

    topic, paginator, page_list = get_paginator(page, topics, per_page=20)
    # collect:前台判断topic是否属于收藏,与收藏按钮的状态变动.
    content = {
        'title': user_nickname,
        'user': user,
        'topics': topic,
        'page': page,
        'paginator': paginator,
        'page_list': page_list,
        'collect': collect,
        'home_page': True
    }
    return render(request, template_name='user/index.html', context=content)


def settings(request):
    """个人帐号设置界面"""

    user = get_user(request)
    content = {
        'title': '账号设置',
        'user': user
    }
    return render(request, template_name='user/settings.html', context=content)


def bind_email(request):
    """绑定邮箱
    message:前台提示绑定结果信息.
    """
    user = get_user(request)
    # 当用户已绑定邮箱的情况下,返回邮箱已绑定信息.
    if user.email:
        return HttpResponseRedirect(reverse('user:settings') + '?message=bind-email-Already')
    else:
        email = request.POST.get('email')
        code = request.POST.get('Vcode')

        # 当Vcode创建时间大于5分钟前的时间则Vcode为有效,否则即为无效.
        v = judgment_code(user_user=user.user, code=code, period_of_validity=5)
        # 如果user与code匹配,并且Vcode为有效,则表明验证通过.进行邮箱绑定.
        if v:
            user.email = email
            user.save()
            message = '?message=bind-email-success'
            # 验证成功立即删除Vcode
            v.delete()
        else:
            message = '?message=code-error'
        return HttpResponseRedirect(reverse('user:settings') + message)


def modify_password(request):
    """修改密码,需要登入权限
    """
    # 获取用户实例
    user = get_user(request)
    password = request.POST.get('password')
    password_repeat = request.POST.get('password_repeat')
    # 先判断两次密码是否一致,不一致直接返回错误消息 or 密码不符合LoginForm验证条件
    if password != password_repeat or not LoginForm({'user': user.user, 'password': password}).is_valid():
        return HttpResponseRedirect(reverse('user:settings') + '?message=password_repeatInconsistent')

    code = request.POST.get('Vcode')
    # code与有效期都符合条件judgment返回v实例,否则返回None
    v = judgment_code(user_user=user.user, code=code, period_of_validity=5)
    if v:
        # 修改密码,registered()方法将密码加密并且保存数据.最后删除v实例,使code失效.
        user.password = password
        user.registered()
        v.delete()
        # 密码修改成功,退出登录.
        return HttpResponseRedirect(reverse('user:logout'))
    else:
        # code错误或code已失效,在前台给出错误提示.
        return HttpResponseRedirect(reverse('user:settings') + '?message=code-error')


def modify_personal_information(request):
    """修改个人信息:头像与签名."""

    user = get_user(request)
    file = request.FILES.get('avatar')
    # 如果存在file,and表达式才会继续判断.先判断尺寸是否大于2M再判断后缀是否合法.
    if file and file.size < 2 * 1024 ** 2:
        suffix = file.name.split('.')[1].lower()
        if suffix in ['jpg', 'png']:
            d = save_img(file, filename=f'{user.nickname}.{suffix}', folder='avatar/')
            # 头像路以static开头而不是/static,和FileField字段的upload_to函数行为保持一致.
            user.avatar = d['src'][1:]
    # 获取签名的值.
    try:
        signature = request.POST.get('signature', '')
        user.signature = signature
        user.save()
    except BaseException as err:
        print(err)
        raise Http404('签名过长,最大长度为48个字符.')
    return HttpResponseRedirect(reverse('user:settings'))


def application_reset_password(request):
    """申请重置密码界面与发送唯一验证码code.
    :return:
    """
    content = {
        'title': '密码找回'
    }
    if request.method == 'GET':
        return render(request, template_name='user/application_reset.html', context=content)
    else:
        userID = request.POST.get('user')
        u = User.objects.filter(user=userID).first()
        # 如果用户存在并且用户已绑定邮箱,生成200位长度的唯一验证码至用户邮箱.
        if u and u.email:
            # 生成验证码
            code = generate_code(user=u.user, length=200)
            # 生成信息
            message = f"你正在申请重置密码:\n点击链接进行密码重置,链接有效期为5分钟.\n" \
                      f"{DOMAIN_NAME + reverse('user:reset_password',args=[code,])}  " \
                      f"\n 如非你本人操作，请忽略此邮件。"
            # 发送邮件
            send_mail(to_addr=u.email, message=message)
            return HttpResponseRedirect(reverse('user:application_reset_password') + '?message=ResetLinksHasBeenSent')
        else:
            return HttpResponseRedirect(reverse('user:application_reset_password') + '?message=userDoesNotExist')


def reset_password(request, code):
    """重置密码界面与修改密码操作.
    :param code: 唯一验证码,有效期5分钟.
    :return:
    """
    content = {
        'title': '重置密码',
        'code': code
    }
    # GET请求跳转重置界面
    if request.method == 'GET':
        return render(request, template_name='user/reset_password.html', context=content)
    else:
        password = request.POST.get('password')
        password_repeat = request.POST.get('password_repeat')
        f = LoginForm({'user': 'repeat', 'password': password})

        # 验证密码是否符合规范与两次密码是否一致
        if f.is_valid() and password == password_repeat:
            v = judgment_code(user_user=None, code=code, period_of_validity=5)
            if v:
                # 通过v找到用户实例, 修改用户密码, 加密密码并且保存.
                user = User.objects.filter(user=v.user).first()
                user.password = password
                user.registered()
                # 删除code的实例v
                v.delete()
                return HttpResponseRedirect(reverse('home') + '?message=ResetPasswordSuccess')
            else:
                # 前台错误消息提示
                content.update({'error': '重置失败,请检查链接有效期.'})
        else:
            # 前台错误消息提示
            content.update({'error': '重置失败,请检查密码是否符合规范.'})
        return render(request, template_name='user/reset_password.html', context=content)


def leave_message(request):
    """接收留言请求视图, 此视图需要登入权限装饰器.
    :return:

templates/user/application_reset.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}

{% endblock %}
{% block body %}
    <form action="{% url 'user:application_reset_password' %}" method="post">
        {% csrf_token %}
        <div class="margin-top-100">
            <div class="width-340 height-250 margin-auto">
                <div>
                    <h1 class="font-bold font-size-24 margin-0">找回密码</h1>
                    <h2 class="color-gray margin-0 font-size-16 font-width-400">验证码将会发送至你的注册邮箱或手机</h2>
                </div>
                <div class="reset_password_inputDIV">
                    <input type="text" placeholder="登入账号" class="border-none outline-none width-100 height-40"
                           name="user">
                </div>
                <input type="submit" value="提交" class="btn width-100 margin-top-5 background-black color-white fa-hover">
            </div>
        </div>
    </form>
{% endblock %}

templates/user/dialog.html
{#{% for message in messages %}#}
{#    <div style="display: block" class="dialog_body {% if message.user.nickname == self %}all-right{% else %}all-left{% endif %}">#}
{#        <div style="display: block">#}
{#            <a href="{% url 'user:user_index' message.user.nickname %}">#}
{#                <img src="{{ message.user.avatar }}" alt="{{ message.user.nickname }}" class="small-avatar">#}
{#            </a>#}
{#        </div>#}
{#        <div class="dialog_content">#}
{#            <div style="display: block">{{ message.content }}</div>#}
{#        </div>#}
{#    </div>#}
{#    <div class="row"></div>#}
{#{% endfor %}#}

templates/user/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}
    <link rel="stylesheet" href="{% static 'css/user/index.css' %}">
{% endblock %}
{% block body %}
    <div class="background-gray">
        <div class="container user_index_body">
            <div class="user_basis">
                <div class="user_avatar">
                    <img src="/{{ user.avatar }}" alt="" class="user_index_avatar">
                </div>
                <div class="user_data background-white">
                    <div>
                        <h1><span>{{ user.nickname }}</span><span
                                class="user_index_signature">{{ user.signature }}</span></h1>
                    </div>
                    <div class="user_medal">
                        &nbsp;
                    </div>
                    <div class="side-container">
                        <div class="side-button">
                            {% if USER %}
                                {% if USER.user == user.user %}
                                    <a href="
                                        {% if collect %}
                                        {% url 'user:user_index' user.nickname %}
                                        {% else %}
                                        {% url 'user:user_index' user.nickname %}?collect=True
                                        {% endif %}"
                                       class="menu-btn margin-left24 fa-hover decoration-none color-black padding-3
                                        {% if collect %}menu-btn-hover{% endif %}">
                                        <span><i class="fa fa-folder-open"></i></span>&nbsp;收藏夹
                                    </a>
                                    <a href="{% url 'user:settings' %}"
                                       class="menu-btn margin-left24 fa-hover color-black decoration-none padding-3"><span><i
                                            class="fa fa-edit"></i></span>编辑资料
                                    </a>
                                {% else %}
                                    <button class="menu-btn margin-lf5 fa-hover" data-toggle="modal"
                                            data-target="#leaveAMessage"><span><i
                                            class="fa fa-envelope"></i></span>&nbsp;留言
                                    </button>
                                {% endif %}
                            {% else %}
                                <button class="menu-btn margin-lf5 fa-hover" data-toggle="modal"
                                        data-target="#leaveAMessage"><span>
                                    <i class="fa fa-envelope"></i></span>&nbsp;留言
                                </button>
                            {% endif %}
                            <div class="modal fade" id="leaveAMessage" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                &times;
                                            </button>
                                            <h5 class="modal-title" id="myModalLabel">
                                                正在给 <span class="font-bold font-size-18">{{ user.nickname }}</span>
                                                留言...
                                            </h5>
                                        </div>
                                        <div class="modal-body">
                                            <div class="padding-lr-25px">
                                                <div class="row display-flex margin-bottom-10">
                                                    <img src="/{{ user.avatar }}" class="small-avatar"
                                                         alt="{{ user.nickname }}">
                                                    <span class="margin-top-18">:有事请给我留言.</span>
                                                </div>
                                                <div class="row">
                                                    <form action="{% url 'user:leave_message' %}" method="post">
                                                        {% csrf_token %}
                                                        <input type="text" name="to_user" value="{{ user.nickname }}"
                                                               hidden>
                                                        <textarea name="content" cols="50" rows="10"
                                                                  class="form-control"></textarea>
                                                        <input type="submit" value="发送留言" class="width-100 border-none">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="user_dynamic">
                <div>
                    {% if collect %}
                        <h3>收藏夹</h3>
                    {% else %}
                        <h3>TA的话题:</h3>
                    {% endif %}
                    {% for topic in topics %}
                        {% include 'topic/topic_list.html' %}
                    {% endfor %}
                    {% include 'pagination.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/mailbox.html
{% extends 'base.html' %}
{% load user_tags %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}{% endblock %}
{% block body %}
    <div class="container padding-all-0 contact_container">
        <div class="contact_left">
            <div style="height: 40px">信箱</div>
            <div>
                <ul class="list-group contact_list">
                    {% if contacts %}
                        {% for contact in contacts %}
                            <li class="contact-li padding-3" data-name="{{ contact.sender__nickname }}"
                                id="{{ contact.sender__nickname }}" data-count="0">
                                <div>
                                    <img src="/{{ contact.sender__avatar }}" alt="avatar"
                                         class="small-avatar"><i
                                        class="badge message_count">{% unread_count contact.sender USER.user %}</i>
                                </div>
                                <span class="contact_nickname">{{ contact.sender__nickname }}</span>
                                <a href="javascript:;" onclick="delMessage(this)"
                                   data-nickname="{{ contact.sender__nickname }}"
                                   class="decoration-none color-none line-height-30">X</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="contact_body">
            <div class="contact_body_title" id="contact_body_title"></div>
            <div class="contact_body_body" id="contact_body" style="overflow: auto;">
            </div>
            <div id="leave-div" class="hidden margin-top-10">
                <input type="text" name="to_user" hidden id="to_user">
                <input type="text" class="form-control" id="m-content" placeholder="回车发送留言"
                       onkeypress="leaveAMessage()">
            </div>
        </div>
    </div>
    <script src="{% static 'js/user/message.js' %}"></script>
{% endblock %}

templates/user/reset_password.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}

{% endblock %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="margin-top-100">
            <div class="width-340 height-250 margin-auto">
                {% if error %}
                    <div class="alert alert-danger padding-all-0">
                        <button type="button" class="close" data-dismiss="alert"
                                aria-hidden="true">
                            &times;
                        </button>
                        {{ error }}</div>
                {% endif %}
                <div>
                    <div>
                        <h1 class="font-bold font-size-24 margin-0">设置新密码</h1>
                        <h2 class="color-gray margin-0 font-size-16 font-width-400">密码长度应大于1小于48.</h2>
                    </div>
                </div>
                <div class="reset_password_inputDIV">
                    <input type="password" name="password"
                           class="border-none outline-none width-100 height-40 font-size-2em"
                           placeholder="请输入密码">
                    <p style="border-bottom: solid 1px #cecece"></p>
                    <input type="password" name="password_repeat"
                           class="border-none outline-none width-100 height-40 font-size-2em"
                           placeholder="请输入密码">
                </div>
                <input type="submit" class="btn background-green width-100 color-white" value="提交">
            </div>

        </div>
    </form>
{% endblock %}

templates/user/settings.html
{% extends 'base.html' %}
{% load user_tags %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block resources %}{% endblock %}
{% block body %}
    <div class="container">
        <form action="{% url 'user:modify_personal_information' %}" method="post" enctype="multipart/form-data">
            <div style="display: block;padding: 5px 0;;margin: 10px 0">
                <label for="avatar">头像</label>
                <img src="/{{ user.avatar }}" alt="头像" class="user_avatar" style="float: none">
                <div style="display: inline-grid;margin-left: 55px;" class="reSignature-div">
                    <a href="javascript:;" class="reSignature-button"> 修改</a>
                    <input type="file" class="hidden" name="avatar" placeholder="xx">
                </div>
            </div>
            <div style="display: block;padding: 5px 0;;margin: 10px 0">
                <label for="signature">签名</label>
                <div style="display: inline-grid;margin-left: 100px;" class="reSignature-div">
                    <span class="color-black">{{ user.signature }}<a href="javascript:;"
                                                                     class="reSignature-button"> 修改</a></span>

                    {% csrf_token %}
                    <input type="text" placeholder="签名" name="signature" id="signature" class="form-control hidden"
                           value="{{ user.signature }}">
                    <input type="submit" class="btn btn-primary hidden" value="提交">
                </div>
            </div>
        </form>
        <div style="display: block;padding: 5px 0;margin: 10px 0">
            <label for="email">邮箱</label>
            {% if user.email %}
                <div style="display: inline-grid;margin-left: 100px;">
                    <span>{{ user.email }}</span>
                </div>
            {% else %}
                <div style="display: inline-grid;margin-left: 100px;" class="bindEmail-div">
                    <span class="color-black bindEmail-button"><a href="javascript:;">绑定邮箱</a></span>
                    <form action="{% url 'user:bind_email' %}" method="post">
                        {% csrf_token %}
                        <div class="display-flex">
                            <input type="text" hidden value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                            <input type="email" placeholder="请输入邮箱" class="form-control hidden" name="email"
                                   id="bindEmail">
                            <button class="hidden line-height-30 border-none background-gray padding-all-0"
                                    style="min-width: 111px" id="Vcode-btn">发送验证码
                            </button>
                        </div>
                        <input type="text" name="Vcode" placeholder="请输入收到的验证码" class="form-control hidden">
                        <input class="btn btn-primary hidden" value="提交" type="submit">
                    </form>
                </div>
            {% endif %}
        </div>
        <div style="display: block;padding: 5px 0;margin: 10px 0">
            <label for="rePassword">帐号密码</label>
            {% if user.email %}
                <div style="display: inline-grid;margin-left: 72px;">
                    <span class="editPassword-button"><a href="javascript:;">修改密码</a></span>
                    <div class="editPassword-div">
                        <form action="{% url 'user:modify_password' %}" method="post">
                            {% csrf_token %}
                            <input type="password" placeholder="请输入密码" class="form-control hidden" name="password">
                            <input type="password" placeholder="请再次输入" class="form-control hidden"
                                   name="password_repeat">
                            <input type="text" placeholder="请输入验证码" class="form-control hidden" name="Vcode">
                            <button class="hidden line-height-30 border-none background-gray padding-all-0"
                                    style="min-width: 111px" id="Vcode-btn2">发送验证码
                            </button>
                            <input type="submit" value="提交" class="btn btn-primary hidden">
                        </form>
                    </div>
                </div>
            {% else %}
                <div style="display: inline-grid;margin-left: 72px;">
                    <span>请先绑定邮箱</span>
                </div>
            {% endif %}
        </div>
    </div>
    <script src="{% static 'js/user/settings.js' %}"></script>
{% endblock %}